name: Build Flipper App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # (Optional but helps on fresh runners)
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi

      - name: Install ufbt
        run: |
          python -m pip install --upgrade pip
          pip install ufbt
          ufbt --version

      - name: Build app
        working-directory: ./erhu_tuner
        run: |
          ufbt update || true
          ufbt build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: erhu_tuner_build
          path: erhu_tuner/build/**
